# sayFloat ← "/mnt/0AD47A53D47A414D/Users/brian/Persinal/Scripts/APL/raylib-apl/breakapl/zig-out/lib/libbreakapl.so" •FFI ""‿"sayFloat"‿"i32"‿"i32"‿"f32"‿"f32"‿"{u8,u8,u8,u8}"
# SayFloat 0‿0‿0‿0‿(0‿0‿0‿0)

# sayI8←"/mnt/0AD47A53D47A414D/Users/brian/Persinal/Scripts/APL/raylib-apl/breakapl/zig-out/lib/libbreakapl.so" •FFI ""‿"sayI8"‿"i8"‿"i8"‿"i8"‿"i8"‿"i8"‿"{u64,{u64,u32},u8}"
# SayI8 1‿2‿3‿4‿5‿(6‿(7‿8)‿9)

ret←"/mnt/0AD47A53D47A414D/Users/brian/Persinal/Scripts/APL/raylib-apl/breakapl/zig-out/lib/libbreakapl.so" •FFI "u64"‿"ret"
•SHow Ret⟨⟩
